# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(username: "Yeetboi", password_digest: "password")
User.create(username: "Yeetgirl", password_digest: "password2")
User.create(username: "JimHarkk", password_digest: "password2")
User.create(username: "PamBees", password_digest: "password2")
User.create(username: "ShirleyTemps", password_digest: "password2")
User.create(username: "SamTarPits", password_digest: "password2")
User.create(username: "TheLegend27", password_digest: "password2")
User.create(username: "TheRealWillSmith", password_digest: "password2")
User.create(username: "JaysPlays", password_digest: "password2")
User.create(username: "YeartieBurtie", password_digest: "password2")
User.create(username: "TweetySweetie", password_digest: "password2")
User.create(username: "YargonDaGod", password_digest: "password2")
User.create(username: "Y-Bot", password_digest: "password2")
User.create(username: "youtoobpoop", password_digest: "password2")
User.create(username: "JocelynFlores", password_digest: "password2")
Topic.create(title: "Cat Pics or GTFO", description: "Plz moar cats or die.")
Topic.create(title: "Meme-a-Palooza", description: "Plz moar memes or die.")
Topic.create(title: "BeggarsBeChoosy", description: "Plz moar beggars or die.")
Topic.create(title: "Memes-n-Chill", description: "Memes and chill vibes all-around.")
Topic.create(title: "Cat-Ladies-R-Cool", description: "Being a cat lady is a way of life. My cats all wear leather jackets.")
Topic.create(title: "Rich-Hobos", description: "These people reallty be trippin.")
Topic.create(title: "Meming-for-Likes", description: "Plz give me moar likes plz.")
Post.create(title: "Yeet", content: "This is a post.", img_url: "www.images-of-dogs.com", user_id: 1, topic_id: 1)
Post.create(title: "Cat", content: "This is a post.", img_url: "", user_id: 1, topic_id: 5)
Post.create(title: "Meme", content: "This is a post.", img_url: "", user_id: 1, topic_id: 3)
Post.create(title: "Beggar", content: "This is a post.", img_url: "", user_id: 1, topic_id: 2)
Post.create(title: "meme-yeet", content: "This is a post.", img_url: "www.images-of-dogs.com", user_id: 1, topic_id: 3)
Post.create(title: "cat-yeet", content: "This is a post.", img_url: "", user_id: 1, topic_id: 7)
Post.create(title: "beggar-yeet", content: "This is a post.", img_url: "www.images-of-dogs.com", user_id: 1, topic_id: 2)
Post.create(title: "meme-haha", content: "This is a post.", img_url: "", user_id: 1, topic_id: 3)
Post.create(title: "cat-haha", content: "This is a post.", img_url: "", user_id: 1, topic_id: 4)
Post.create(title: "beggar-haha", content: "This is a post.", img_url: "www.images-of-dogs.com", user_id: 1, topic_id: 6)
Like.create(user_id: 1, post_id: 1)
Like.create(user_id: 2, post_id: 1)
Like.create(user_id: 3, post_id: 1)
Like.create(user_id: 4, post_id: 1)
Like.create(user_id: 5, post_id: 1)
Like.create(user_id: 1, post_id: 2)
Like.create(user_id: 1, post_id: 3)
Like.create(user_id: 1, post_id: 4)
Like.create(user_id: 1, post_id: 5)
Like.create(user_id: 1, post_id: 6)
Like.create(user_id: 2, post_id: 4)
Like.create(user_id: 3, post_id: 4)
Like.create(user_id: 4, post_id: 4)
Like.create(user_id: 7, post_id: 4)
Like.create(user_id: 14, post_id: 2)
Like.create(user_id: 13, post_id: 3)
Like.create(user_id: 12, post_id: 4)
Like.create(user_id: 11, post_id: 5)
Like.create(user_id: 10, post_id: 6)
Like.create(user_id: 9, post_id: 7)
Like.create(user_id: 8, post_id: 8)
Like.create(user_id: 12, post_id: 9)
